### ISSUE TITLE
NN VA!

### ISSUE THREAD

**Issue by SorPampurio** [funnydog/frenchiov#1]
NN VA! La denuncerò ai caraBBinieri! Le manderò gli zingri in casa!

PS. Pentiti!

**Comment by funnydog** [comment]
LOL! Hola Lichene!

Che errore ti da?

**Comment by funnydog** [comment]
no più visto, si logga su steam ma come invisibile perciò non posso contattarlo... magari stasera passo a fare un giro in chat verso le 8.30-9.00, anche se l'ambiente è corrosivo.

Mmmhh... penso di aver risolto il problema chiudiamo l'issue!
